-- MySQL Script generated by MySQL Workbench
-- Wed Jan  5 15:06:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esports` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `esports` ;

-- -----------------------------------------------------
-- Table `esports`.`sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`sponsor` ;

CREATE TABLE IF NOT EXISTS `esports`.`sponsor` (
  `Nome` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`squadra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`squadra` ;

CREATE TABLE IF NOT EXISTS `esports`.`squadra` (
  `Nome` VARCHAR(50) NOT NULL,
  `Nazionalità` VARCHAR(50) NOT NULL,
  `Anno_fondazione` YEAR NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`accordo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`accordo` ;

CREATE TABLE IF NOT EXISTS `esports`.`accordo` (
  `Codice` INT NOT NULL AUTO_INCREMENT,
  `Premio` FLOAT NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Data_fine` DATE NOT NULL,
  `Sponsor` VARCHAR(50) NOT NULL,
  `Squadra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Codice`),
  CONSTRAINT `accordo_ibfk_1`
    FOREIGN KEY (`Sponsor`)
    REFERENCES `esports`.`sponsor` (`Nome`),
  CONSTRAINT `accordo_ibfk_2`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Squadra_Sponsor_UNIQUE` ON `esports`.`accordo` (`Squadra` ASC, `Sponsor` ASC) INVISIBLE;

CREATE INDEX `accordo_ibfk_1` ON `esports`.`accordo` (`Sponsor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`allenatore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`allenatore` ;

CREATE TABLE IF NOT EXISTS `esports`.`allenatore` (
  `Id` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Cognome` VARCHAR(50) NOT NULL,
  `Data_nascita` DATE NOT NULL,
  `Nazionalità` VARCHAR(50) NULL DEFAULT NULL,
  `Tipo` ENUM('MENTAL COACH', 'ASSISTANT COACH', 'POSITION COACH', 'STRATEGIC COACH', 'HEAD COACH') NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Stipendio` FLOAT NOT NULL,
  `Squadra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `allenatore_ibfk_1`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `allenatore_ibfk_1` ON `esports`.`allenatore` (`Squadra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`campioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`campioni` ;

CREATE TABLE IF NOT EXISTS `esports`.`campioni` (
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`giocatore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`giocatore` ;

CREATE TABLE IF NOT EXISTS `esports`.`giocatore` (
  `Id` VARCHAR(25) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Cognome` VARCHAR(100) NOT NULL,
  `Sesso` ENUM('M', 'F') NOT NULL,
  `Data_di_nascita` DATE NOT NULL,
  `Nazionalità` VARCHAR(40) NOT NULL,
  `Ruolo` ENUM('Top', 'Jng', 'Mid', 'Adc', 'Supp') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`contratto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`contratto` ;

CREATE TABLE IF NOT EXISTS `esports`.`contratto` (
  `Codice` INT NOT NULL AUTO_INCREMENT,
  `Data_inizio` DATE NOT NULL,
  `Data_fine` DATE NOT NULL,
  `Stipendio` FLOAT NOT NULL,
  `Scaduto` TINYINT(1) NOT NULL DEFAULT '0',
  `Squadra` VARCHAR(50) NOT NULL,
  `Giocatore` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Codice`),
  CONSTRAINT `giocatore firmato`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`giocatore` (`Id`),
  CONSTRAINT `squadra2`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `giocatore_squadra_UNIQUE` ON `esports`.`contratto` (`Data_inizio` ASC, `Squadra` ASC, `Giocatore` ASC) VISIBLE;

CREATE INDEX `squadra2_idx` ON `esports`.`contratto` (`Squadra` ASC) VISIBLE;

CREATE INDEX `giocatore firmato_idx` ON `esports`.`contratto` (`Giocatore` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`torneo` ;

CREATE TABLE IF NOT EXISTS `esports`.`torneo` (
  `Nome` VARCHAR(255) NOT NULL,
  `tipo` ENUM('REGIONALE', 'NAZIONALE', 'MONDIALE') NOT NULL,
  `Montepremi` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`edizioni_torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`edizioni_torneo` ;

CREATE TABLE IF NOT EXISTS `esports`.`edizioni_torneo` (
  `Torneo` VARCHAR(50) NOT NULL,
  `Anno` YEAR NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Data_fine` DATE NOT NULL,
  `Squadra_vincitrice` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Torneo`, `Anno`),
  CONSTRAINT `edizioni_torneo_ibfk_1`
    FOREIGN KEY (`Torneo`)
    REFERENCES `esports`.`torneo` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`statistiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`statistiche` ;

CREATE TABLE IF NOT EXISTS `esports`.`statistiche` (
  `Giocatore` VARCHAR(25) NOT NULL,
  `Uccisioni` INT NOT NULL,
  `Morti` INT NOT NULL,
  `Assist` INT NOT NULL,
  PRIMARY KEY (`Giocatore`),
  CONSTRAINT `statistiche_ibfk_1`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`giocatore` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`giocati`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`giocati` ;

CREATE TABLE IF NOT EXISTS `esports`.`giocati` (
  `Giocatore` VARCHAR(25) NOT NULL,
  `Campione` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Giocatore`, `Campione`),
  CONSTRAINT `giocati_ibfk_1`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`statistiche` (`Giocatore`),
  CONSTRAINT `giocati_ibfk_2`
    FOREIGN KEY (`Campione`)
    REFERENCES `esports`.`campioni` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Campione` ON `esports`.`giocati` (`Campione` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`staff` ;

CREATE TABLE IF NOT EXISTS `esports`.`staff` (
  `Id` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Cognome` VARCHAR(50) NOT NULL,
  `Data_nascita` DATE NOT NULL,
  `Incarico` VARCHAR(50) NULL DEFAULT NULL,
  `Stipendio` FLOAT NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Proprietario` TINYINT(1) NOT NULL DEFAULT '0',
  `Squadra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `staff_ibfk_1`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Squadra` ON `esports`.`staff` (`Squadra` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`manager` ;

CREATE TABLE IF NOT EXISTS `esports`.`manager` (
  `Nickname` VARCHAR(50) NOT NULL,
  `Reparto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Nickname`),
  CONSTRAINT `Nickname`
    FOREIGN KEY (`Nickname`)
    REFERENCES `esports`.`staff` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`partita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`partita` ;

CREATE TABLE IF NOT EXISTS `esports`.`partita` (
  `Codice` INT NOT NULL AUTO_INCREMENT,
  `Turno` TINYINT NOT NULL,
  `Fase` ENUM('FASE A GIRONI', 'OTTAVI', 'QUARTI', 'SEMIFINALE', 'FINALE') NOT NULL,
  `Risultato` VARCHAR(10) NULL DEFAULT NULL,
  `Data_partita` DATE NOT NULL,
  `Torneo` VARCHAR(50) NOT NULL,
  `Anno_torneo` YEAR NOT NULL,
  `Squadra1` VARCHAR(50) NOT NULL,
  `Squadra2` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Codice`),
  CONSTRAINT `partita_ibfk_1`
    FOREIGN KEY (`Torneo` , `Anno_torneo`)
    REFERENCES `esports`.`edizioni_torneo` (`Torneo` , `Anno`),
  CONSTRAINT `partita_ibfk_2`
    FOREIGN KEY (`Squadra1`)
    REFERENCES `esports`.`squadra` (`Nome`),
  CONSTRAINT `partita_ibfk_3`
    FOREIGN KEY (`Squadra2`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `data_partita_unique` ON `esports`.`partita` (`Squadra1` ASC, `Squadra2` ASC, `Data_partita` ASC, `Turno` ASC) VISIBLE;

CREATE INDEX `Torneo` ON `esports`.`partita` (`Torneo` ASC, `Anno_torneo` ASC) INVISIBLE;

CREATE INDEX `Squadra1` ON `esports`.`partita` (`Squadra1` ASC) INVISIBLE;

CREATE INDEX `Squadra2` ON `esports`.`partita` (`Squadra2` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`vinto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`vinto` ;

CREATE TABLE IF NOT EXISTS `esports`.`vinto` (
  `Giocatore` VARCHAR(25) NOT NULL,
  `Torneo` VARCHAR(50) NOT NULL,
  `Anno` YEAR NOT NULL,
  PRIMARY KEY (`Giocatore`, `Torneo`, `Anno`),
  CONSTRAINT `vinto_ibfk_1`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`giocatore` (`Id`),
  CONSTRAINT `vinto_ibfk_2`
    FOREIGN KEY (`Torneo` , `Anno`)
    REFERENCES `esports`.`edizioni_torneo` (`Torneo` , `Anno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Torneo` ON `esports`.`vinto` (`Torneo` ASC, `Anno` ASC) INVISIBLE;

USE `esports` ;

-- -----------------------------------------------------
-- Placeholder table for view `esports`.`giocatori_ventenni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`giocatori_ventenni` (`Nickname` INT, `Nome` INT, `Cognome` INT, `Età` INT);

-- -----------------------------------------------------
-- Placeholder table for view `esports`.`info_trofei_giocatori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`info_trofei_giocatori` (`Giocatore` INT, `Squadra` INT, `count(*)` INT);

-- -----------------------------------------------------
-- Placeholder table for view `esports`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`proprietario` (`Id` INT, `Nome` INT, `Cognome` INT, `Data_nascita` INT, `Squadra` INT, `Stipendio` INT);

-- -----------------------------------------------------
-- Placeholder table for view `esports`.`trofei_squadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`trofei_squadra` (`Nome` INT, `tipo` INT, `count(*)` INT);

-- -----------------------------------------------------
-- procedure nuovoContratto
-- -----------------------------------------------------

USE `esports`;
DROP procedure IF EXISTS `esports`.`nuovoContratto`;

DELIMITER $$
USE `esports`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `nuovoContratto`(Data_inizio date, Data_fine date, Stipendio float, Scaduto boolean, Squadra varchar(50), Giocatore varchar(25))
BEGIN
	update contratto set Scaduto = 1 where(current_date() > data_fine);
    INSERT INTO `esports`.`contratto` (`Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`)
    VALUES (Data_inizio, Data_fine, Stipendio, Scaduto, Squadra, Giocatore);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function rateo
-- -----------------------------------------------------

USE `esports`;
DROP function IF EXISTS `esports`.`rateo`;

DELIMITER $$
USE `esports`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `rateo`(u int, m int, a int) RETURNS float
    NO SQL
    DETERMINISTIC
BEGIN
	DECLARE rateo float(2);
    SET rateo = (u+a)/m;
    RETURN rateo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure new_Victorius
-- -----------------------------------------------------

USE `esports`;
DROP procedure IF EXISTS `esports`.`new_Victorius`;

DELIMITER $$
USE `esports`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `new_Victorius`(IN g varchar(50), IN torneo varchar(50), IN y year)
BEGIN
	INSERT INTO vinto(Giocatore,Torneo,Anno) VALUES (g,torneo,y);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure take_victory_players
-- -----------------------------------------------------

USE `esports`;
DROP procedure IF EXISTS `esports`.`take_victory_players`;

DELIMITER $$
USE `esports`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `take_victory_players`(IN squad varchar(50),IN torneo varchar(50), IN anno YEAR, IN inizio DATE, IN fine DATE)
BEGIN
	DECLARE i INT DEFAULT 0;
	SET @n = (SELECT count(Giocatore) FROM contratto as c WHERE c.Squadra = squad AND c.Data_inizio <= inizio AND c.Data_fine >= fine);
    ciclo:LOOP
		IF (i = @n) THEN -- Se sono stati inseriti tutti i giocatori, termina il loop
			LEAVE ciclo;
        END IF;
        -- Estraggo i nomi dei giocatori che giocavano in quella squadra al momento della vittoria,1 alla volta
        SET @g = (SELECT Giocatore 
					FROM contratto as c
					WHERE c.Squadra = squad AND c.Data_inizio <= inizio AND c.Data_fine >= fine
					LIMIT i,1);
		CALL new_Victorius(@g,torneo,anno); -- inserisco in vinto il giocatore ed il torneo da lui vinto
		SET i = i+1; -- incremento il contatore
    END LOOP;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `esports`.`giocatori_ventenni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`giocatori_ventenni`;
DROP VIEW IF EXISTS `esports`.`giocatori_ventenni` ;
USE `esports`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `esports`.`giocatori_ventenni` (`Nickname`,`Nome`,`Cognome`,`Età`) AS select `esports`.`giocatore`.`Id` AS `Id`,`esports`.`giocatore`.`Nome` AS `Nome`,`esports`.`giocatore`.`Cognome` AS `Cognome`,(year(curdate()) - year(`esports`.`giocatore`.`Data_di_nascita`)) AS `year(CURDATE())-year(Data_di_nascita)` from `esports`.`giocatore` where ((year(curdate()) - year(`esports`.`giocatore`.`Data_di_nascita`)) < 20);

-- -----------------------------------------------------
-- View `esports`.`info_trofei_giocatori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`info_trofei_giocatori`;
DROP VIEW IF EXISTS `esports`.`info_trofei_giocatori` ;
USE `esports`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `esports`.`info_trofei_giocatori` (`Giocatore`,`Squadra`,`Num_trofei`) AS select `v`.`Giocatore` AS `Giocatore`,`et`.`Squadra_vincitrice` AS `Squadra`,count(0) AS `count(*)` from ((`esports`.`vinto` `v` join `esports`.`torneo` `t`) join `esports`.`edizioni_torneo` `et`) where ((`v`.`Torneo` = `et`.`Torneo`) and (`v`.`Anno` = `et`.`Anno`) and (`t`.`Nome` = `et`.`Torneo`)) group by `v`.`Giocatore`,`Squadra`;

-- -----------------------------------------------------
-- View `esports`.`proprietario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`proprietario`;
DROP VIEW IF EXISTS `esports`.`proprietario` ;
USE `esports`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `esports`.`proprietario` (`Id`,`Nome`,`Cognome`,`Data_nascita`,`Squadra`,`Stipendio`) AS select `esports`.`staff`.`Id` AS `Id`,`esports`.`staff`.`Nome` AS `Nome`,`esports`.`staff`.`Cognome` AS `Cognome`,`esports`.`staff`.`Data_nascita` AS `Data_nascita`,`esports`.`staff`.`Squadra` AS `Squadra`,`esports`.`staff`.`Stipendio` AS `Stipendio` from `esports`.`staff` where (`esports`.`staff`.`Proprietario` = 1) order by `esports`.`staff`.`Squadra`;

-- -----------------------------------------------------
-- View `esports`.`trofei_squadra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`trofei_squadra`;
DROP VIEW IF EXISTS `esports`.`trofei_squadra` ;
USE `esports`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `esports`.`trofei_squadra` (`Squadra`,`Tipo`,`Vittorie`) AS select `s`.`Nome` AS `Nome`,`t`.`tipo` AS `tipo`,count(0) AS `count(*)` from ((`esports`.`squadra` `s` join `esports`.`torneo` `t`) join `esports`.`edizioni_torneo` `et`) where ((`s`.`Nome` = `et`.`Squadra_vincitrice`) and (`t`.`Nome` = `et`.`Torneo`)) group by `s`.`Nome`,`t`.`tipo`;
USE `esports`;

DELIMITER $$

USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_contratto_non_scaduto` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_contratto_non_scaduto`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	IF((SELECT Scaduto FROM contratto 
		WHERE (new.Giocatore = Giocatore) 
        ORDER BY Scaduto ASC
        limit 1) = 0) THEN
			signal sqlstate '45000' set message_text = 'Il giocatore ha ancora un contratto attivo, impossibile inserirne uno nuovo';
	END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_dates` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_dates`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	if(new.data_fine <= new.data_inizio) then
		signal sqlstate '45000' set message_text = 'Il contratto non può scadere prima di iniziare.';
    end if;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_max_player` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_max_player`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	if ((select count(*) from Contratto
			where(new.Squadra = Squadra and 
			Scaduto = 0)) >= 7) then
		signal sqlstate '45000' 
        set message_text = 'Impossibile aggiungere nuovo giocatore, la squadra ha raggiunto il massimo di giocatori nella rosa';
	end if;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Value_Scaduto_errato` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Value_Scaduto_errato`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	if(new.Data_fine < current_date()) then
		SET new.Scaduto = 1;
    end if;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_if_scaduto` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_if_scaduto`
BEFORE UPDATE ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	IF (new.Data_Fine < current_date()) THEN
		Set new.Scaduto = 1;
    END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_edition_after2011` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_edition_after2011`
BEFORE INSERT ON `esports`.`edizioni_torneo`
FOR EACH ROW
BEGIN
	IF (new.Anno < 2011) THEN
		signal sqlstate '45000' set message_text = 'Non esistono tornei con data antecedente al 2011';
    END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Aggiornamento_vittorie_giocatori` $$
USE `esports`$$
CREATE DEFINER = CURRENT_USER TRIGGER `esports`.`Aggiornamento_vittorie_giocatori`
AFTER INSERT ON `edizioni_torneo`
FOR EACH ROW
BEGIN
	-- Richiama "take_victory_player" per inserire tutti i giocatori della squadra vincitrice dentro la tabella "vinto"
	CALL take_victory_players(new.Squadra_vincitrice,new.Torneo,new.Anno,new.Data_inizio,new.Data_fine);
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_Tournament_validity` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_Tournament_validity`
BEFORE INSERT ON `esports`.`partita`
FOR EACH ROW
BEGIN
    SET @inizio = (select Data_inizio from Edizioni_torneo
        where (Torneo = new.Torneo and Anno = new.Anno_torneo)); -- Salvo la data di inizio dell'edizione del torneo
    SET @fine = (select Data_fine from Edizioni_torneo
        where (Torneo = new.Torneo and Anno = new.Anno_torneo)); -- Salvo la data di fine dell'edizione del torneo
    
    -- Controllo Squadra 1 --
 
    SET @dateLM1 = (select ((select Data_partita from Partita
    where (new.Squadra1 = Squadra1 or new.Squadra1 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo la data dell'ultimo match. Se non è presente, ritorna null
    
    SET @tournamentLM1 = (select ((select Torneo from Partita
    where (new.Squadra1 = Squadra1 or new.Squadra1 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo il torneo dell'ultiomo match giocato. Se non è presente, ritorna null
    
    
    IF (@tournamentLM1 <> new.Torneo) THEN
        IF (@dateLM1 >= @inizio and @dateLM1 <= @fine) THEN
            signal sqlstate '45000' set message_text = 'La squadra 1 sta gia partecipando ad un torneo. Impossibile inserire la nuova partita';
        END IF;
    END IF;
    
    -- Controllo Squadra 2 --
    
    SET @dateLM2 = (select ((select Data_partita from Partita
    where (new.Squadra2 = Squadra1 or new.Squadra2 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo la data dell'ultimo match. Se non è presente, ritorna null
    
    SET @tournamentLM2 = (select ((select Torneo from Partita
    where (new.Squadra2 = Squadra1 or new.Squadra2 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo il torneo dell'ultiomo match giocato. Se non è presente, ritorna null
    
    IF (@tournamentLM2 <> new.Torneo) THEN
        IF (@dateLM2 >= @inizio and @dateLM2 <= @fine) THEN
            signal sqlstate '45000' set message_text = 'La squadra 2 sta gia partecipando ad un torneo. Impossibile inserire la nuova partita';
        END IF;
    END IF;
 
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_after_2011` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_after_2011`
BEFORE INSERT ON `esports`.`partita`
FOR EACH ROW
BEGIN
	IF (year(new.data_partita) < 2011) THEN
		signal sqlstate '45000' set message_text = 'Non esistono partite con data antecedente al 2011';
    END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_phase_date` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_phase_date`
BEFORE INSERT ON `esports`.`partita`
FOR EACH ROW
BEGIN
	SET @lastPhase =  (select fase from Partita 
						where (new.Torneo = Torneo and new.Anno_Torneo = Anno_torneo)
						Order by Data_partita DESC
						limit 1);
	SET @lastDate = (select Data_partita from Partita 
					where (new.Torneo = Torneo and new.Anno_Torneo = Anno_torneo)
					Order by Data_partita DESC
					limit 1);
        
	IF (new.fase != @lastPhase)THEN
		IF (new.Data_partita < @lastDate) THEN -- controllo l'inserimento di una partita con data antecedente a quella dell'ultima partita nel db
			CASE new.fase
				WHEN 'OTTAVI' THEN 
					IF (@lastPhase ='FASE A GIRONI') THEN 
						signal sqlstate '45000' set message_text = 'Una partita giocata agli ottavi non può avere data antecedente ad una partita della fase a gironi';
                    END IF;
				WHEN 'QUARTI' THEN
					IF(@lastPhase ='OTTAVI' or @lastPhase ='FASE A GIRONI') THEN
						signal sqlstate '45000' set message_text = 'Una partita giocata ai quarti non può avere data antecedente ad una partita della fase a gironi o degli ottavi';
					END IF;
				WHEN 'SEMIFINALE' THEN
					IF(@lastPhase = 'QUARTI' or @lastPhase ='OTTAVI' or @lastPhase ='FASE A GIRONI') THEN
						signal sqlstate '45000' set message_text = 'Una partita giocata alle semifinali non può avere data antecedente ad una partita della fase a gironi,degli ottavi o dei quarti';
					END IF;
				WHEN 'FINALE' THEN
					IF(@lastPhase = 'SEMIFINALE' or @lastPhase = 'QUARTI' or @lastPhase ='OTTAVI' or @lastPhase ='FASE A GIRONI') THEN
						signal sqlstate '45000' set message_text = 'Una finale non può avere data antecedente ad una partita della fase a gironi,degli ottavi,dei quarti o delle semifinali';
					END IF;
			END CASE;
        else 
			CASE new.fase
				WHEN 'FINALE' THEN
					if(new.Turno < (select turno from Partita 
						where (new.Torneo = Torneo and new.Anno_Torneo = Anno_torneo and Fase = 'FINALE')
						Order by Data_partita DESC
						limit 1)) THEN
                        signal sqlstate '45000' set message_text = 'Turno errato';
					end if;
				WHEN 'FASE A GIRONI' THEN 
					IF (@lastPhase ='SEMIFINALE' OR @lastPhase = 'QUARTI' OR @lastPhase = 'FINALE' or @lastPhase = 'OTTAVI') THEN 
						signal sqlstate '45000' set message_text = 'Una partita giocata durante la fase a gironi non può avere data successiva rispetto alle partite nelle fasi seguenti';
					END IF;
				WHEN 'OTTAVI' THEN 
					IF (@lastPhase ='SEMIFINALE' OR @lastPhase = 'QUARTI' OR @lastPhase = 'FINALE') THEN 
						signal sqlstate '45000' set message_text = 'Una partita giocata agli ottavi non può avere data successiva alle partite delle fasi seguenti';
					END IF;
				WHEN 'QUARTI' THEN
					IF(@lastPhase ='SEMIFINALE' OR @lastPhase = 'FINALE') THEN
						signal sqlstate '45000' set message_text = 'Una partita giocata ai quarti non può avere data successiva alle partite giocate in semifinale o in finale';
					END IF;
				WHEN 'SEMIFINALE' THEN
					IF(@lastPhase = 'FINALE') THEN
						signal sqlstate '45000' set message_text = 'Una semifinale non può avere data successiva rispetto alla finale';
					END IF;
				END CASE;
		END IF;
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `esports`.`sponsor`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('Razer', 'Informatica');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('Nike', 'Sportswear');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('Adidas', 'Sportswear');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('OPPO', 'Informatica');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('BMW', 'Autovetture');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('Monster Energy', 'Bevanda energetica');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('AMD', 'Informatica');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('Oneplus', 'Informatica');
INSERT INTO `esports`.`sponsor` (`Nome`, `Tipo`) VALUES ('Luiss Vuitton', 'Moda');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`squadra`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('DWG KIA', 'Corea del sud', 2017);
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('EDward Gaming', 'Cina', 2013);
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('T1', 'Corea del sud', 2012);
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('Fnatic', 'Inghilterra', 2011);
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('G2 Esports', 'Germania', 2016);
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('Cloud9', 'USA', 2012);
INSERT INTO `esports`.`squadra` (`Nome`, `Nazionalità`, `Anno_fondazione`) VALUES ('FunPlus Phoenix', 'Cina', 2017);

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`accordo`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`accordo` (`Codice`, `Premio`, `Data_inizio`, `Data_fine`, `Sponsor`, `Squadra`) VALUES (1, 10000, '2017-02-20', '2022-02-20', 'Razer', 'DWG KIA');
INSERT INTO `esports`.`accordo` (`Codice`, `Premio`, `Data_inizio`, `Data_fine`, `Sponsor`, `Squadra`) VALUES (2, 25000, '2015-05-10', '2020-01-10', 'AMD', 'T1');
INSERT INTO `esports`.`accordo` (`Codice`, `Premio`, `Data_inizio`, `Data_fine`, `Sponsor`, `Squadra`) VALUES (3, 50000, '2017-02-20', '2018-06-05', 'Luiss Vuitton', 'Fnatic');
INSERT INTO `esports`.`accordo` (`Codice`, `Premio`, `Data_inizio`, `Data_fine`, `Sponsor`, `Squadra`) VALUES (4, 35000, '2019-03-19', '2021-03-16', 'Oneplus', 'FunPlus Phoenix');
INSERT INTO `esports`.`accordo` (`Codice`, `Premio`, `Data_inizio`, `Data_fine`, `Sponsor`, `Squadra`) VALUES (5, 45000, '2021-04-15', '2022-01-12', 'OPPO', 'T1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`allenatore`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('CorGi', 'Cheng', 'Pin-Lun', '1993-08-08', 'Tailandia', 'STRATEGIC COACH', '2019-12-16', 25000, 'EDward Gaming');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Clearlove', 'Mink', 'Kai', '1993-07-03', 'Cina', 'HEAD COACH', '2019-12-13', 35000, 'EDward Gaming');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Steal', 'Chou', 'Lu-Hsi', '1992-08-15', 'Tailandia', 'HEAD COACH', '2018-11-14', 40000, 'FunPlus Phoenix');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('River', 'Wang', 'Yang', '1994-10-14', 'Cina', 'ASSISTANT COACH', '2019-12-01', 40000, 'FunPlus Phoenix');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('YamatoCannon', 'Jakob', 'Mebdi', '1995-12-30', 'Svezia', 'HEAD COACH', '2020-11-01', 35000, 'Fnatic');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Shaves', 'Kevin Edward', 'Tolman', '1996-01-16', 'Inghilterra', 'STRATEGIC COACH', '2021-05-17', 25000, 'Fnatic');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Dylan Falco', 'Dylan', 'Falco', '1992-03-05', 'Canada', 'HEAD COACH', '2021-12-01', 40000, 'G2 Esports');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Nelson', 'Sng', 'Yi-Wei', '1992-01-01', 'Singapore', 'STRATEGIC COACH', '2021-05-11', 29000, 'G2 Esports');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Moment', 'Kim', 'Ji-Hwan', '1933-12-19', 'Corea del sud', 'HEAD COACH', '2021-07-16', 35000, 'T1');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('kk0ma', 'Kim', 'Jeong-gyun', '1985-12-23', 'Corea del sud', 'HEAD COACH', '2021-12-11', 40000, 'DWG KIA');
INSERT INTO `esports`.`allenatore` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Nazionalità`, `Tipo`, `Data_inizio`, `Stipendio`, `Squadra`) VALUES ('Veigar v2', 'Marius', 'Aune', '1999-12-01', 'Norvegia', 'POSITION COACH', '2021-08-12', 35000, 'Cloud9');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`campioni`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Aatrox');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ahri');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Akali');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Akshan');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Alistar');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Amumu');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Anivia');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Annie');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Aphelios');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ashe');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Aurelion Sol');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Azir');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Bard');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Blitzcrank');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Brand');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Braum');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Caitlyn');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Camille');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Cassiopeia');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Cho\'Gath');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Corki');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Darius');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Diana');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Draven');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Dr. Mundo');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ekko');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Elise');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Evelynn');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ezreal');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Fiddlesticks');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Fiora');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Fizz');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Galio');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Gangplank');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Garen');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Gnar');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Gragas');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Graves');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Gwen');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Hecarim');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Heimerdinger');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Illaoi');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Irelia');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ivern');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Janna');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Jarvan IV');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Jax');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Jayce');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Jhin');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Jinx');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kai\'Sa');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kalista');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Karma');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Karthus');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kassadin');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Katarina');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kayle');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kayn');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kennen');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kha\'Zix');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kindred');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kled');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Kog\'Maw');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('LeBlanc');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Lee Sin');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Leona');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Lillia');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Lissandra');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Lucian');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Lulu');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Lux');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Malphite');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Malzahar');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Maokai');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Master Yi');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Miss Fortune');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Wukong');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Mordekaiser');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Morgana');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Nami');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Nasus');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Nautilus');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Neeko');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Nidalee');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Nocturne');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Nunu & Willump');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Olaf');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Orianna');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ornn');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Pantheon');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Poppy');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Pyke');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Qiyana');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Quinn');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Rakan');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Rammus');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Rek\'Sai');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Rell');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Renekton');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Rengar');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Riven');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Rumble');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ryze');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Samira');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Sejuani');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Senna');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Seraphine');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Sett');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Shaco');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Shen');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Shyvana');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Singed');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Sion');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Sivir');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Skarner');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Sona');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Soraka');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Swain');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Sylas');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Syndra');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Tahm Kench');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Taliyah');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Talon');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Taric');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Teemo');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Thresh');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Tristana');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Trundle');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Tryndamere');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Twisted Fate');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Twitch');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Udyr');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Urgot');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Varus');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Vayne');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Veigar');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Vel\'Koz');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Vex');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Vi');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Viego');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Viktor');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Vladimir');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Volibear');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Warwick');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Xayah');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Xerath');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Xin Zhao');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Yasuo');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Yone');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Yorick');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Yuumi');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Zac');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Zed');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Ziggs');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Zilean');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Zoe');
INSERT INTO `esports`.`campioni` (`Nome`) VALUES ('Zyra');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`giocatore`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('xiaolaohu', 'Ping', 'Xiao-hu', 'M', '2002-08-22', 'Cina', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Beichuan', 'Yang', 'Ling', 'M', '2001-07-21', 'Cina', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Gori', 'Kim', 'Tae-woo', 'M', '2000-8-9', 'Corea del sud', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('jiang', 'Luo', 'Bai-Jiang', 'M', '2000-10-2', 'Cina', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Lwx', 'Liu', 'Wei-Xiang', 'M', '1998-10-24', 'Cina', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Hang', 'Fu', 'Ming-Hang', 'M', '2003-02-5', 'Cina', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Lele', 'Dang', 'Bo-Lin', 'M', '2000-07-11', 'Cina', 'Supp ');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Summit', 'Park', 'Woo-tae', 'M', '1998-12-8', 'Corea del sud', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Blaber', 'Robert', 'Huang', 'M', '2000-01-4', 'USA', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Fudge', 'Ibrahim', 'Allami', 'M', '2002-05-23', 'Australia', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Berserker', 'Kim', 'Min-cheol', 'M', '2003-05-25', 'Corea del sud', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Zven', 'Jesper', 'Svenningsen', 'M', '1997-06-24', 'Danimarca', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Isles', 'Jonah', 'Rosario', 'M', '2001-03-7', 'Australia', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Broken Blade', 'Sergen', 'Celik', 'M', '2000-01-19', 'Germania', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Targamas', 'Raphael', 'CrabbÃ©', 'M', '2000-06-30', 'Belgio', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Jankos', 'Marcin', 'Jankowski', 'M', '1995-06-23', 'Polonia', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('caPs', 'Rasmis', 'Borregaard Winther', 'M', '1999-11-17', 'Danimarca', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Flakked', 'Victor', 'Lirola', 'M', '2001-04-25', 'Spagna', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Mikyx', 'Mihael', 'Mehle', 'M', '1998-11-2', 'Slovenia', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Wunder', 'Martin', 'Nordah Hansen', 'M', '1998-11-9', 'Danimarca', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Razork', 'Ivan', 'MartÃ¬n DÃ¬az', 'M', '2000-10-7', 'Spagna', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Upset', 'Elias', 'Lipp', 'M', '1999-12-16', 'Germania', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Hylissang', 'Zdravets', 'Illiev Galabov', 'M', '1995-04-30', 'Bulgaria', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Nisqy', 'Yasin', 'Dincer', 'M', '1998-07-28', 'Belgio', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Zeus', 'Choi', 'Woo-je', 'M', '2004-01-31', 'Corea del sud', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Oner', 'Moon', 'Hyeon-joon', 'M', '2002-12-24', 'Corea del sud', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Faker', 'Lee', 'Sang-hyeok', 'M', '1996-05-7', 'Corea del sud', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Gumayusi', ' Lee', 'Min-hyeong', 'M', '2002-02-6', 'Corea del sud', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Keria', 'Ryu', 'Min-seok', 'M', '2002-02-14', 'Corea del sud', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Burdol', 'Noh', 'Tae-yoon', 'M', '2003-12-25', 'Corea del sud', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Hoya', 'Yoon', 'Yong-ho', 'M', '2000-08-25', 'Corea del sud', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Canyon', 'Kim', 'Geon-bu', 'M', '2001-06-18', 'Corea del sud', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('ShowMaker', 'Heo', 'Su', 'M', '2000-07-22', 'Corea del sud', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('deokdam', 'Seo', 'Dae-gil', 'M', '2000-02-25', 'Corea del sud', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Kellin', 'Kim', 'Hyeong-gyu', 'M', '2001-02-1', 'Corea del sud', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Flandre', 'Li', 'Xuan-Jun', 'M', '1998-08-28', 'Cina', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Xiaoxiang', 'Huang', 'Xiang', 'M', '2002-03-18', 'Cina', 'Top');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Jiejie', 'Zhao', 'Li-jie', 'M', '2001-10-27', 'Cina', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Scout', 'Lee', 'Ya-chan', 'M', '1998-03-14', 'Corea del sud', 'Mid');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Viper', 'Park', 'Do-hyeon', 'M', '2000-10-19', 'Corea del sud', 'Adc');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Meiko', 'Tian', 'Ye', 'M', '1998-06-6', 'Cina', 'Supp');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Clearlove', 'Ming', 'Kai', 'M', '1993-07-25', 'Cina', 'Jng');
INSERT INTO `esports`.`giocatore` (`Id`, `Nome`, `Cognome`, `Sesso`, `Data_di_nascita`, `Nazionalità`, `Ruolo`) VALUES ('Hope', 'Wang', 'Jie', 'M', '2000-09-29', 'Cina', 'Adc');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`contratto`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (1, '2021-12-01', '2022-11-21', 20000, 0, 'DWG KIA', 'Burdol');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (2, '2021-07-08', '2022-11-22', 35000, 0, 'FunPlus Phoenix', 'xiaolaohu');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (3, '2021-12-16', '2023-11-21', 40000, 0, 'FunPlus Phoenix', 'Beichuan');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (4, '2021-12-15', '2023-11-12', 30000, 0, 'FunPlus Phoenix', 'Gori');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (5, '2021-12-16', '2022-11-22', 30000, 0, 'FunPlus Phoenix', 'jiang');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (6, '2017-12-21', '2022-11-22', 50000, 0, 'FunPlus Phoenix', 'Lwx');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (7, '2021-12-15', '2022-12-15', 20000, 0, 'FunPlus Phoenix', 'Hang');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (8, '2021-12-15', '2022-12-15', 20000, 0, 'FunPlus Phoenix', 'Lele');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (9, '2021-11-20', '2024-11-19', 45000, 0, 'Cloud9', 'Summit');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (10, '2018-07-21', '2025-11-18', 45000, 0, 'Cloud9', 'Blaber');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (11, '2020-10-30', '2025-11-18', 35000, 0, 'Cloud9', 'Fudge');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (12, '2021-11-20', '2024-11-19', 35000, 0, 'Cloud9', 'Berserker');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (13, '2021-06-22', '2024-11-19', 42000, 0, 'Cloud9', 'Zven');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (14, '2021-11-20', '2024-11-19', 32400, 0, 'Cloud9', 'Isles');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (15, '2021-12-03', '2023-11-24', 25000, 0, 'G2 Esports', 'Broken Blade');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (16, '2021-12-03', '2022-11-20', 20000, 0, 'G2 Esports', 'Targamas');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (17, '2017-12-08', '2022-11-21', 36000, 0, 'G2 Esports', 'Jankos');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (18, '2018-11-29', '2023-11-20', 45000, 0, 'G2 Esports', 'caPs');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (19, '2021-12-03', '2022-12-04', 35000, 0, 'G2 Esports', 'Flakked');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (20, '2018-11-29', '2022-11-21', 30000, 0, 'G2 Esports', 'Mikyx');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (21, '2021-12-10', '2024-11-18', 35000, 0, 'Fnatic', 'Wunder');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (22, '2021-12-10', '2024-11-18', 35000, 0, 'Fnatic', 'Razork');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (23, '2020-11-26', '2023-11-20', 45000, 0, 'Fnatic', 'Upset');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (24, '2017-12-14', '2023-11-20', 40000, 0, 'Fnatic', 'Hylissang');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (25, '2020-11-24', '2023-11-20', 27000, 0, 'Fnatic', 'Nisqy');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (26, '2020-11-26', '2022-11-21', 36500, 0, 'T1', 'Zeus');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (27, '2020-12-01', '2023-11-20', 35000, 0, 'T1', 'Oner');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (28, '2019-12-08', '2023-11-20', 50000, 0, 'T1', 'Faker');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (29, '2019-12-08', '2023-11-20', 35000, 0, 'T1', 'Gumayusi');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (30, '2020-11-17', '2022-11-15', 25666, 0, 'T1', 'Keria');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (31, '2021-12-01', '2022-11-21', 25000, 0, 'DWG KIA', 'Hoya');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (32, '2021-12-01', '2023-11-20', 30000, 0, 'DWG KIA', 'Canyon');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (33, '2021-12-01', '2023-11-20', 45000, 0, 'DWG KIA', 'ShowMaker');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (34, '2021-12-01', '2023-11-20', 40000, 0, 'DWG KIA', 'deokdam');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (35, '2021-12-01', '2023-11-20', 35000, 0, 'DWG KIA', 'Kellin');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (36, '2020-12-16', '2022-11-20', 30000, 0, 'EDward Gaming', 'Flandre');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (37, '2021-06-02', '2023-11-21', 35000, 0, 'EDward Gaming', 'Xiaoxiang');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (38, '2019-04-22', '2023-11-21', 30000, 0, 'EDward Gaming', 'Jiejie');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (39, '2016-03-23', '2022-11-21', 40000, 0, 'EDward Gaming', 'Scout');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (40, '2020-12-16', '2021-11-16', 35000, 1, 'EDward Gaming', 'Viper');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (41, '2014-12-17', '2022-11-21', 40000, 0, 'EDward Gaming', 'Meiko');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (42, '2020-12-14', '2021-05-01', 35000, 1, 'EDward Gaming', 'Clearlove');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (43, '2021-06-02', '2021-12-31', 30000, 1, 'EDward Gaming', 'Hope');
INSERT INTO `esports`.`contratto` (`Codice`, `Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`) VALUES (44, '2021-05-03', '2022-11-21', 35000, 0, 'Cloud9', 'Clearlove');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`torneo`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`torneo` (`Nome`, `tipo`, `Montepremi`) VALUES ('Season World Championship', 'Mondiale', 2225000);
INSERT INTO `esports`.`torneo` (`Nome`, `tipo`, `Montepremi`) VALUES ('Mid Season Invitational', 'Mondiale', 1000000);
INSERT INTO `esports`.`torneo` (`Nome`, `tipo`, `Montepremi`) VALUES ('MLG Summer Arena', 'Nazionale', 50000);
INSERT INTO `esports`.`torneo` (`Nome`, `tipo`, `Montepremi`) VALUES ('IEF', 'Nazionale', 3500);
INSERT INTO `esports`.`torneo` (`Nome`, `tipo`, `Montepremi`) VALUES ('IWCT', 'Mondiale', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`edizioni_torneo`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Season World Championship', 2021, '2021-10-05', '2021-11-06', 'EDward Gaming');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Season World Championship', 2020, '2020-09-25', '2020-10-31', 'G2 Esports');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Season World Championship', 2019, '2019-10-02', '2019-11-10', 'FunPlus Phoenix');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Season World Championship', 2018, '2018-10-01', '2018-11-03', 'Fnatic');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Season World Championship', 2017, '2017-09-23', '2017-11-04', 'T1');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Season World Championship', 2016, '2016-09-29', '2016-10-29', 'T1');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Mid Season Invitational', 2017, '2017-04-28', '2017-05-21', 'T1');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('Mid Season Invitational', 2019, '2019-05-01', '2019-05-19', 'G2 Esports');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('IEF', 2016, '2016-05-02', '2016-05-25', 'Cloud9');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('IEF', 2017, '2017-04-01', '2017-05-2', 'Cloud9');
INSERT INTO `esports`.`edizioni_torneo` (`Torneo`, `Anno`, `Data_inizio`, `Data_fine`, `Squadra_vincitrice`) VALUES ('MLG Summer Arena', 2017, '2017-10-01', '2017-10-20', 'G2 Esports');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`statistiche`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('xiaolaohu', 450, 341, 737);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Beichuan', 371, 273, 789);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Gori', 258, 177, 350);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Lwx', 6006, 1165, 4574);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Hang', 260, 620, 1074);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Lele', 241, 526, 1402);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Summit', 688, 578, 852);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Blaber', 520, 467, 222);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Fudge', 789, 600, 890);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Berserker', 1002, 844, 944);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Zven', 780, 655, 915);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Isles', 250, 111, 389);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Broken Blade', 478, 512, 665);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Targamas', 598, 477, 154);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Jankos', 698, 112, 456);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('caPs', 7500, 4800, 8435);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Flakked', 450, 339, 650);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Mikyx', 698, 452, 396);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Wunder', 999, 326, 1150);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Razork', 467, 259, 666);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Upset', 2988, 1999, 3544);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Hylissang', 4889, 6658, 10000);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Nisqy', 226, 115, 198);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Zeus', 354, 156, 298);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Oner', 751, 658, 850);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Faker', 9555, 7600, 5654);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Gumayusi', 115, 25, 11);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Keria', 681, 669, 1155);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Burdol', 669, 478, 255);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Hoya', 558, 422, 655);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Canyon', 223, 100, 158);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('ShowMaker', 6722, 3899, 4852);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('deokdam', 123, 11, 158);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Kellin', 566, 482, 1000);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Flandre', 785, 445, 1422);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Xiaoxiang', 698, 478, 115);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Jiejie', 999, 658, 664);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Scout', 2548, 1845, 1697);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Viper', 1658, 1105, 910);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Meiko', 846, 545, 450);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Clearlove', 687, 698, 698);
INSERT INTO `esports`.`statistiche` (`Giocatore`, `Uccisioni`, `Morti`, `Assist`) VALUES ('Hope', 1111, 847, 556);

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`giocati`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('xiaolaohu', 'Camille');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('xiaolaohu', 'Gnar');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('xiaolaohu', 'Aatrox');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('xiaolaohu', 'Jayce');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Beichuan', 'Xin Zhao');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Beichuan', 'Diana');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Beichuan', 'Nidalee');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Gori', 'Akali');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Gori', 'Orianna');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Gori', 'Ryze');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Gori', 'Sett');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Lwx', 'Kai\'Sa');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Lwx', 'Varus');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Lwx', 'Aphelios');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Lwx', 'Caitlyn');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Lwx', 'Ezreal');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Hang', 'Nautilus');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Hang', 'Tahm Kench');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Hang', 'Braum');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Hang', 'Alistar');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Hang', 'Rakan');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Lele', 'Thresh');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Summit', 'Aatrox');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Summit', 'Jayce');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Summit', 'Gnar');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Blaber', 'Lee Sin');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Blaber', 'Gragas');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Blaber', 'Kindred');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Fudge', 'Camille');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Fudge', 'Gangplank');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Zven', 'Ezreal');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Zven', 'Varus');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Zven', 'Sivir');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Zven', 'Kai\'Sa');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Jankos', 'Lee Sin');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Jankos', 'Elise');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Jankos', 'Gragas');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Jankos', 'Rek\'Sai');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('caPs', 'Syndra');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('caPs', 'Ryze');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('caPs', 'LeBlanc');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('caPs', 'Orianna');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('caPs', 'Zoe');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Upset', 'Ezreal');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Upset', 'Kai\'sa');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Upset', 'Tristana');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Upset', 'Xayah');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Faker', 'Azir');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Faker', 'Ryze');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Faker', 'LeBlanc');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Faker', 'Orianna');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('ShowMaker', 'Zoe');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('ShowMaker', 'Syndra');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('ShowMaker', 'Akali');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Scout', 'Azir');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Scout', 'Irelia');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Scout', 'Zoe');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Scout', 'Orianna');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Viper', 'Ezreal');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Viper', 'Kai\'Sa');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Viper', 'Lucian');
INSERT INTO `esports`.`giocati` (`Giocatore`, `Campione`) VALUES ('Viper', 'Kalista');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`staff`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('No1', 'Lee', 'Yu-yeong', '1986-06-15', 'CEO', 60000, '2017-05-05', 1, 'DWG KIA');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('KDG', 'Kim', 'Dong-gyu', '1988-01-25', 'Manager', 45000, '2019-04-04', 0, 'DWG KIA');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('Denny', 'Cao', 'Feng', '1987-04-15', 'Leader', 75000, '2019-03-19', 1, 'FunPlus Phoenix');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('Sean', 'Gu', 'Xiong-Cheng', '1991-03-15', 'Analyst', 28000, '2020-06-06', 0, 'FunPlus Phoenix');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('JM', 'Jeo', 'Marsh', '1978-12-12', 'CEO', 100000, '2020-02-14', 1, 'T1');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('GBM', 'Lee', 'Chang-seok', '1994-06-23', 'Streamer', 35000, '2021-02-01', 0, 'T1');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('SM', 'Samuel', 'Mathews', '1988-02-01', 'Co-Founder', 70000, '2011-01-01', 1, 'Fnatic');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('AM', 'Anne', 'Mathews', '1991-05-11', 'Co-Founder', 70000, '2011-01-01', 1, 'Fnatic');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('Jack', 'Jack', 'Etienne', '1972-12-26', 'CEO and Founder', 125000, '2013-05-23', 1, 'Cloud9');
INSERT INTO `esports`.`staff` (`Id`, `Nome`, `Cognome`, `Data_nascita`, `Incarico`, `Stipendio`, `Data_inizio`, `Proprietario`, `Squadra`) VALUES ('Sneaky', 'Zachary', 'Scuderi', '1994-03-19', 'Consulente', 70000, '2020-01-16', 0, 'Cloud9');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`manager`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`manager` (`Nickname`, `Reparto`) VALUES ('KDG', 'Generali');

COMMIT;


-- -----------------------------------------------------
-- Data for table `esports`.`partita`
-- -----------------------------------------------------
START TRANSACTION;
USE `esports`;
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (1, 1, 'QUARTI', '0-1', '2021-10-23', 'Season World Championship', 2021, 'EDward Gaming', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (2, 2, 'QUARTI', '0-2', '2021-10-23', 'Season World Championship', 2021, 'EDward Gaming', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (3, 3, 'QUARTI', '1-2', '2021-10-23', 'Season World Championship', 2021, 'EDward Gaming', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (4, 4, 'QUARTI', '2-2', '2021-10-23', 'Season World Championship', 2021, 'EDward Gaming', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (5, 5, 'QUARTI', '3-2', '2021-10-23', 'Season World Championship', 2021, 'EDward Gaming', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (6, 1, 'QUARTI', '1-0', '2021-10-24', 'Season World Championship', 2021, 'DWG KIA', 'Fnatic');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (7, 2, 'QUARTI', '2-0', '2021-10-24', 'Season World Championship', 2021, 'DWG KIA', 'Fnatic');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (8, 3, 'QUARTI', '3-0', '2021-10-24', 'Season World Championship', 2021, 'DWG KIA', 'Fnatic');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (9, 1, 'SEMIFINALE', '0-1', '2021-10-30', 'Season World Championship', 2021, 'T1', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (10, 2, 'SEMIFINALE', '1-1', '2021-10-30', 'Season World Championship', 2021, 'T1', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (11, 3, 'SEMIFINALE', '1-2', '2021-10-30', 'Season World Championship', 2021, 'T1', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (12, 4, 'SEMIFINALE', '2-2', '2021-10-30', 'Season World Championship', 2021, 'T1', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (13, 5, 'SEMIFINALE', '2-3', '2021-10-30', 'Season World Championship', 2021, 'T1', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (14, 1, 'SEMIFINALE', '1-0', '2021-10-31', 'Season World Championship', 2021, 'DWG KIA', 'FunPlus Phoenix');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (15, 2, 'SEMIFINALE', '2-0', '2021-10-31', 'Season World Championship', 2021, 'DWG KIA', 'FunPlus Phoenix');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (16, 3, 'SEMIFINALE', '3-0', '2021-10-31', 'Season World Championship', 2021, 'DWG KIA', 'FunPlus Phoenix');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (17, 1, 'FINALE', '1-0', '2021-11-06', 'Season World Championship', 2021, 'DWG KIA', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (18, 2, 'FINALE', '2-0', '2021-11-06', 'Season World Championship', 2021, 'DWG KIA', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (19, 3, 'FINALE', '2-1', '2021-11-06', 'Season World Championship', 2021, 'DWG KIA', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (20, 4, 'FINALE', '2-2', '2021-11-06', 'Season World Championship', 2021, 'DWG KIA', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (21, 5, 'FINALE', '2-3', '2021-11-06', 'Season World Championship', 2021, 'DWG KIA', 'EDward Gaming');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (22, 1, 'FASE A GIRONI', '1-0', '2019-05-10', 'Mid Season Invitational', 2019, 'T1', 'Fnatic');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (23, 1, 'FASE A GIRONI', '0-1', '2019-05-10', 'Mid Season Invitational', 2019, 'FunPlus Phoenix', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (24, 1, 'FASE A GIRONI', '1-0', '2019-05-11', 'Mid Season Invitational', 2019, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (25, 1, 'FASE A GIRONI', '0-1', '2019-05-11', 'Mid Season Invitational', 2019, 'FunPlus Phoenix', 'Fnatic');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (26, 1, 'FASE A GIRONI', '1-0', '2019-05-12', 'Mid Season Invitational', 2019, 'T1', 'FunPlus Phoenix');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (27, 1, 'FASE A GIRONI', '1-0', '2019-05-12', 'Mid Season Invitational', 2019, 'G2 Esports', 'Fnatic');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (28, 1, 'FINALE', '0-1', '2019-05-14', 'Mid Season Invitational', 2019, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (29, 2, 'FINALE', '0-2', '2019-05-14', 'Mid Season Invitational', 2019, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (30, 3, 'FINALE', '0-3', '2019-05-14', 'Mid Season Invitational', 2019, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (31, 1, 'SEMIFINALE', '1-0', '2016-10-14', 'Season World Championship', 2016, 'Cloud9', 'DWG KIA');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (32, 2, 'SEMIFINALE', '2-0', '2016-10-14', 'Season World Championship', 2016, 'Cloud9', 'DWG KIA');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (33, 3, 'SEMIFINALE', '3-0', '2016-10-14', 'Season World Championship', 2016, 'Cloud9', 'DWG KIA');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (34, 1, 'SEMIFINALE', '1-0', '2016-10-15', 'Season World Championship', 2016, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (35, 2, 'SEMIFINALE', '1-1', '2016-10-15', 'Season World Championship', 2016, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (36, 3, 'SEMIFINALE', '2-1', '2016-10-15', 'Season World Championship', 2016, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (37, 4, 'SEMIFINALE', '2-2', '2016-10-15', 'Season World Championship', 2016, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (38, 5, 'SEMIFINALE', '3-2', '2016-10-15', 'Season World Championship', 2016, 'T1', 'G2 Esports');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (39, 1, 'FINALE', '1-0', '2016-10-20', 'Season World Championship', 2016, 'T1', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (40, 2, 'FINALE', '1-1', '2016-10-20', 'Season World Championship', 2016, 'T1', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (41, 3, 'FINALE', '2-1', '2016-10-20', 'Season World Championship', 2016, 'T1', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (42, 4, 'FINALE', '3-1', '2016-10-20', 'Season World Championship', 2016, 'T1', 'Cloud9');
INSERT INTO `esports`.`partita` (`Codice`, `Turno`, `Fase`, `Risultato`, `Data_partita`, `Torneo`, `Anno_torneo`, `Squadra1`, `Squadra2`) VALUES (43, 1, 'FINALE', '3-0', '2017-10-20', 'MLG Summer Arena', 2017, 'G2 Esports', 'T1');

COMMIT;

