-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 00:42:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema esports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esports` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `esports` ;

-- -----------------------------------------------------
-- Table `esports`.`sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`sponsor` ;

CREATE TABLE IF NOT EXISTS `esports`.`sponsor` (
  `Nome` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`squadra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`squadra` ;

CREATE TABLE IF NOT EXISTS `esports`.`squadra` (
  `Nome` VARCHAR(50) NOT NULL,
  `Nazionalità` VARCHAR(50) NOT NULL,
  `Anno_fondazione` YEAR NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`accordo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`accordo` ;

CREATE TABLE IF NOT EXISTS `esports`.`accordo` (
  `Codice` INT NOT NULL AUTO_INCREMENT,
  `Premio` FLOAT NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Data_fine` DATE NOT NULL,
  `Sponsor` VARCHAR(50) NOT NULL,
  `Squadra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Codice`),
  CONSTRAINT `accordo_ibfk_1`
    FOREIGN KEY (`Sponsor`)
    REFERENCES `esports`.`sponsor` (`Nome`),
  CONSTRAINT `accordo_ibfk_2`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Squadra_Sponsor_UNIQUE` ON `esports`.`accordo` (`Squadra` ASC, `Sponsor` ASC) INVISIBLE;

CREATE INDEX `accordo_ibfk_1` ON `esports`.`accordo` (`Sponsor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`allenatore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`allenatore` ;

CREATE TABLE IF NOT EXISTS `esports`.`allenatore` (
  `Id` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Cognome` VARCHAR(50) NOT NULL,
  `Data_nascita` DATE NOT NULL,
  `Nazionalità` VARCHAR(50) NULL DEFAULT NULL,
  `Tipo` ENUM('MENTAL COACH', 'ASSISTANT COACH', 'POSITION COACH', 'STRATEGIC COACH', 'HEAD COACH') NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Stipendio` FLOAT NOT NULL,
  `Squadra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `allenatore_ibfk_1`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `allenatore_ibfk_1` ON `esports`.`allenatore` (`Squadra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`campioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`campioni` ;

CREATE TABLE IF NOT EXISTS `esports`.`campioni` (
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`giocatore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`giocatore` ;

CREATE TABLE IF NOT EXISTS `esports`.`giocatore` (
  `Id` VARCHAR(25) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Cognome` VARCHAR(100) NOT NULL,
  `Sesso` ENUM('M', 'F') NOT NULL,
  `Data_di_nascita` DATE NOT NULL,
  `Nazionalità` VARCHAR(40) NOT NULL,
  `Ruolo` ENUM('Top', 'Jng', 'Mid', 'Adc', 'Supp') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`contratto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`contratto` ;

CREATE TABLE IF NOT EXISTS `esports`.`contratto` (
  `Codice` INT NOT NULL AUTO_INCREMENT,
  `Data_inizio` DATE NOT NULL,
  `Data_fine` DATE NOT NULL,
  `Stipendio` FLOAT NOT NULL,
  `Scaduto` TINYINT(1) NOT NULL DEFAULT '0',
  `Squadra` VARCHAR(50) NOT NULL,
  `Giocatore` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Codice`),
  CONSTRAINT `giocatore firmato`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`giocatore` (`Id`),
  CONSTRAINT `squadra2`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `giocatore_squadra_UNIQUE` ON `esports`.`contratto` (`Data_inizio` ASC, `Squadra` ASC, `Giocatore` ASC) VISIBLE;

CREATE INDEX `squadra2_idx` ON `esports`.`contratto` (`Squadra` ASC) VISIBLE;

CREATE INDEX `giocatore firmato_idx` ON `esports`.`contratto` (`Giocatore` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`torneo` ;

CREATE TABLE IF NOT EXISTS `esports`.`torneo` (
  `Nome` VARCHAR(255) NOT NULL,
  `tipo` ENUM('REGIONALE', 'NAZIONALE', 'MONDIALE') NOT NULL,
  `Montepremi` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`edizioni_torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`edizioni_torneo` ;

CREATE TABLE IF NOT EXISTS `esports`.`edizioni_torneo` (
  `Torneo` VARCHAR(50) NOT NULL,
  `Anno` YEAR NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Data_fine` DATE NOT NULL,
  `Squadra_vincitrice` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Torneo`, `Anno`),
  CONSTRAINT `edizioni_torneo_ibfk_1`
    FOREIGN KEY (`Torneo`)
    REFERENCES `esports`.`torneo` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`statistiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`statistiche` ;

CREATE TABLE IF NOT EXISTS `esports`.`statistiche` (
  `Giocatore` VARCHAR(25) NOT NULL,
  `Uccisioni` INT NOT NULL,
  `Morti` INT NOT NULL,
  `Assist` INT NOT NULL,
  PRIMARY KEY (`Giocatore`),
  CONSTRAINT `statistiche_ibfk_1`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`giocatore` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`giocati`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`giocati` ;

CREATE TABLE IF NOT EXISTS `esports`.`giocati` (
  `Giocatore` VARCHAR(25) NOT NULL,
  `Campione` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Giocatore`, `Campione`),
  CONSTRAINT `giocati_ibfk_1`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`statistiche` (`Giocatore`),
  CONSTRAINT `giocati_ibfk_2`
    FOREIGN KEY (`Campione`)
    REFERENCES `esports`.`campioni` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Campione` ON `esports`.`giocati` (`Campione` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`staff` ;

CREATE TABLE IF NOT EXISTS `esports`.`staff` (
  `Id` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Cognome` VARCHAR(50) NOT NULL,
  `Data_nascita` DATE NOT NULL,
  `Incarico` VARCHAR(50) NULL DEFAULT NULL,
  `Stipendio` FLOAT NOT NULL,
  `Data_inizio` DATE NOT NULL,
  `Proprietario` TINYINT(1) NOT NULL DEFAULT '0',
  `Squadra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `staff_ibfk_1`
    FOREIGN KEY (`Squadra`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Squadra` ON `esports`.`staff` (`Squadra` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`manager` ;

CREATE TABLE IF NOT EXISTS `esports`.`manager` (
  `Nickname` VARCHAR(50) NOT NULL,
  `Reparto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Nickname`),
  CONSTRAINT `Nickname`
    FOREIGN KEY (`Nickname`)
    REFERENCES `esports`.`staff` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esports`.`partita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`partita` ;

CREATE TABLE IF NOT EXISTS `esports`.`partita` (
  `Codice` INT NOT NULL AUTO_INCREMENT,
  `Turno` TINYINT NOT NULL,
  `Fase` ENUM('FASE A GIRONI', 'OTTAVI', 'QUARTI', 'SEMIFINALE', 'FINALE') NOT NULL,
  `Risultato` VARCHAR(10) NULL DEFAULT NULL,
  `Data_partita` DATE NOT NULL,
  `Torneo` VARCHAR(50) NOT NULL,
  `Anno_torneo` YEAR NOT NULL,
  `Squadra1` VARCHAR(50) NOT NULL,
  `Squadra2` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Codice`),
  CONSTRAINT `partita_ibfk_1`
    FOREIGN KEY (`Torneo` , `Anno_torneo`)
    REFERENCES `esports`.`edizioni_torneo` (`Torneo` , `Anno`),
  CONSTRAINT `partita_ibfk_2`
    FOREIGN KEY (`Squadra1`)
    REFERENCES `esports`.`squadra` (`Nome`),
  CONSTRAINT `partita_ibfk_3`
    FOREIGN KEY (`Squadra2`)
    REFERENCES `esports`.`squadra` (`Nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `data_partita_unique` ON `esports`.`partita` (`Squadra1` ASC, `Squadra2` ASC, `Data_partita` ASC, `Turno` ASC) VISIBLE;

CREATE INDEX `Torneo` ON `esports`.`partita` (`Torneo` ASC, `Anno_torneo` ASC) INVISIBLE;

CREATE INDEX `Squadra1` ON `esports`.`partita` (`Squadra1` ASC) INVISIBLE;

CREATE INDEX `Squadra2` ON `esports`.`partita` (`Squadra2` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `esports`.`vinto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`vinto` ;

CREATE TABLE IF NOT EXISTS `esports`.`vinto` (
  `Giocatore` VARCHAR(25) NOT NULL,
  `Torneo` VARCHAR(50) NOT NULL,
  `Anno` YEAR NOT NULL,
  PRIMARY KEY (`Giocatore`, `Torneo`, `Anno`),
  CONSTRAINT `vinto_ibfk_1`
    FOREIGN KEY (`Giocatore`)
    REFERENCES `esports`.`giocatore` (`Id`),
  CONSTRAINT `vinto_ibfk_2`
    FOREIGN KEY (`Torneo` , `Anno`)
    REFERENCES `esports`.`edizioni_torneo` (`Torneo` , `Anno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Torneo` ON `esports`.`vinto` (`Torneo` ASC, `Anno` ASC) INVISIBLE;

USE `esports` ;

-- -----------------------------------------------------
-- Placeholder table for view `esports`.`giocatori_ventenni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`giocatori_ventenni` (`Nickname` INT, `Nome` INT, `Cognome` INT, `Età` INT);

-- -----------------------------------------------------
-- Placeholder table for view `esports`.`trofei_squadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`trofei_squadra` (`Nome` INT, `tipo` INT, `count(*)` INT);

-- -----------------------------------------------------
-- procedure nuovoContratto
-- -----------------------------------------------------

USE `esports`;
DROP procedure IF EXISTS `esports`.`nuovoContratto`;

DELIMITER $$
USE `esports`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `nuovoContratto`(Data_inizio date, Data_fine date, Stipendio float, Scaduto boolean, Squadra varchar(50), Giocatore varchar(25))
BEGIN
	update contratto set Scaduto = 1 where(current_date() > data_fine);
    INSERT INTO `esports`.`contratto` (`Data_inizio`, `Data_fine`, `Stipendio`, `Scaduto`, `Squadra`, `Giocatore`)
    VALUES (Data_inizio, Data_fine, Stipendio, Scaduto, Squadra, Giocatore);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function rateo
-- -----------------------------------------------------

USE `esports`;
DROP function IF EXISTS `esports`.`rateo`;

DELIMITER $$
USE `esports`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `rateo`(u int, m int, a int) RETURNS float
    NO SQL
    DETERMINISTIC
BEGIN
	DECLARE rateo float(2);
    SET rateo = (u+a)/m;
    RETURN rateo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `esports`.`giocatori_ventenni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`giocatori_ventenni`;
DROP VIEW IF EXISTS `esports`.`giocatori_ventenni` ;
USE `esports`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `esports`.`giocatori_ventenni` (`Nickname`,`Nome`,`Cognome`,`Età`) AS select `esports`.`giocatore`.`Id` AS `Id`,`esports`.`giocatore`.`Nome` AS `Nome`,`esports`.`giocatore`.`Cognome` AS `Cognome`,(year(curdate()) - year(`esports`.`giocatore`.`Data_di_nascita`)) AS `year(CURDATE())-year(Data_di_nascita)` from `esports`.`giocatore` where ((year(curdate()) - year(`esports`.`giocatore`.`Data_di_nascita`)) < 20);

-- -----------------------------------------------------
-- View `esports`.`trofei_squadra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esports`.`trofei_squadra`;
DROP VIEW IF EXISTS `esports`.`trofei_squadra` ;
USE `esports`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `esports`.`trofei_squadra` (`Squadra`,`Tipo`,`Vittorie`) AS select `s`.`Nome` AS `Nome`,`t`.`tipo` AS `tipo`,count(0) AS `count(*)` from ((`esports`.`squadra` `s` join `esports`.`torneo` `t`) join `esports`.`edizioni_torneo` `et`) where ((`s`.`Nome` = `et`.`Squadra_vincitrice`) and (`t`.`Nome` = `et`.`Torneo`)) group by `s`.`Nome`;
USE `esports`;

DELIMITER $$

USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_contratto_non_scaduto` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_contratto_non_scaduto`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	IF((SELECT Scaduto FROM contratto 
		WHERE (new.Giocatore = Giocatore) 
        ORDER BY Scaduto ASC
        limit 1) = 0) THEN
			signal sqlstate '45000' set message_text = 'Il giocatore ha ancora un contratto attivo, impossibile inserirne uno nuovo';
	END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_dates` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_dates`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	if(new.data_fine <= new.data_inizio) then
		signal sqlstate '45000' set message_text = 'Il contratto non può scadere prima di iniziare.';
    end if;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_if_scaduto` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_if_scaduto`
BEFORE UPDATE ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	IF (new.Data_Fine < current_date()) THEN
		Set new.Scaduto = 1;
    END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_max_player` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_max_player`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	if ((select count(*) from Contratto
			where(new.Squadra = Squadra and 
			Scaduto = 0)) >= 7) then
		signal sqlstate '45000' 
        set message_text = 'Impossibile aggiungere nuovo giocatore, la squadra ha raggiunto il massimo di giocatori nella rosa';
	end if;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Value_Scaduto_errato` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Value_Scaduto_errato`
BEFORE INSERT ON `esports`.`contratto`
FOR EACH ROW
BEGIN
	if(new.Data_fine < current_date()) then
		SET new.Scaduto = 1;
    end if;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_edition_after2011` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_edition_after2011`
BEFORE INSERT ON `esports`.`edizioni_torneo`
FOR EACH ROW
BEGIN
	IF (new.Anno < 2011) THEN
		signal sqlstate '45000' set message_text = 'Non esistono tornei con data antecedente al 2011';
    END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_Tournament_validity` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_Tournament_validity`
BEFORE INSERT ON `esports`.`partita`
FOR EACH ROW
BEGIN
    SET @inizio = (select Data_inizio from Edizioni_torneo
        where (Torneo = new.Torneo and Anno = new.Anno_torneo)); -- Salvo la data di inizio dell'edizione del torneo
    SET @fine = (select Data_fine from Edizioni_torneo
        where (Torneo = new.Torneo and Anno = new.Anno_torneo)); -- Salvo la data di fine dell'edizione del torneo
    
    -- Controllo Squadra 1 --
 
    SET @dateLM1 = (select ((select Data_partita from Partita
    where (new.Squadra1 = Squadra1 or new.Squadra1 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo la data dell'ultimo match. Se non è presente, ritorna null
    
    SET @tournamentLM1 = (select ((select Torneo from Partita
    where (new.Squadra1 = Squadra1 or new.Squadra1 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo il torneo dell'ultiomo match giocato. Se non è presente, ritorna null
    
    
    IF (@tournamentLM1 <> new.Torneo) THEN
        IF (@dateLM1 >= @inizio and @dateLM1 <= @fine) THEN
            signal sqlstate '45000' set message_text = 'La squadra 1 sta gia partecipando ad un torneo. Impossibile inserire la nuova partita';
        END IF;
    END IF;
    
    -- Controllo Squadra 2 --
    
    SET @dateLM2 = (select ((select Data_partita from Partita
    where (new.Squadra2 = Squadra1 or new.Squadra2 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo la data dell'ultimo match. Se non è presente, ritorna null
    
    SET @tournamentLM2 = (select ((select Torneo from Partita
    where (new.Squadra2 = Squadra1 or new.Squadra2 = Squadra2) 
    order by Data_partita DESC
    limit 1))); -- Memorizzo il torneo dell'ultiomo match giocato. Se non è presente, ritorna null
    
    IF (@tournamentLM2 <> new.Torneo) THEN
        IF (@dateLM2 >= @inizio and @dateLM2 <= @fine) THEN
            signal sqlstate '45000' set message_text = 'La squadra 2 sta gia partecipando ad un torneo. Impossibile inserire la nuova partita';
        END IF;
    END IF;
 
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_after_2011` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_after_2011`
BEFORE INSERT ON `esports`.`partita`
FOR EACH ROW
BEGIN
	IF (year(new.data_partita) < 2011) THEN
		signal sqlstate '45000' set message_text = 'Non esistono partite con data antecedente al 2011';
    END IF;
END$$


USE `esports`$$
DROP TRIGGER IF EXISTS `esports`.`Check_phase_date` $$
USE `esports`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `esports`.`Check_phase_date`
BEFORE INSERT ON `esports`.`partita`
FOR EACH ROW
BEGIN
	SET @lastPhase =  (select fase from Partita 
						where (new.Torneo = Torneo and new.Anno_Torneo = Anno_torneo)
						Order by Data_partita DESC
						limit 1);
	SET @lastDate = (select Data_partita from Partita 
					where (new.Torneo = Torneo and new.Anno_Torneo = Anno_torneo)
					Order by Data_partita DESC
					limit 1);
        
	IF (new.fase != @lastPhase)THEN
		IF (new.Data_partita < @lastDate) THEN -- controllo l'inserimento di una partita con data antecedente a quella dell'ultima partita nel db
			CASE new.fase
				WHEN 'OTTAVI' THEN 
					IF (@lastPhase ='FASE A GIRONI') THEN 
						signal sqlstate '45000' set message_text = 'Una partita giocata agli ottavi non può avere data antecedente ad una partita della fase a gironi';
                    END IF;
				WHEN 'QUARTI' THEN
					IF(@lastPhase ='OTTAVI' or @lastPhase ='FASE A GIRONI') THEN
						signal sqlstate '45000' set message_text = 'Una partita giocata ai quarti non può avere data antecedente ad una partita della fase a gironi o degli ottavi';
					END IF;
				WHEN 'SEMIFINALE' THEN
					IF(@lastPhase = 'QUARTI' or @lastPhase ='OTTAVI' or @lastPhase ='FASE A GIRONI') THEN
						signal sqlstate '45000' set message_text = 'Una partita giocata alle semifinali non può avere data antecedente ad una partita della fase a gironi,degli ottavi o dei quarti';
					END IF;
				WHEN 'FINALE' THEN
					IF(@lastPhase = 'SEMIFINALE' or @lastPhase = 'QUARTI' or @lastPhase ='OTTAVI' or @lastPhase ='FASE A GIRONI') THEN
						signal sqlstate '45000' set message_text = 'Una finale non può avere data antecedente ad una partita della fase a gironi,degli ottavi,dei quarti o delle semifinali';
					END IF;
			END CASE;
        else 
			CASE new.fase
				WHEN 'FINALE' THEN
					if(new.Turno < (select turno from Partita 
						where (new.Torneo = Torneo and new.Anno_Torneo = Anno_torneo and Fase = 'FINALE')
						Order by Data_partita DESC
						limit 1)) THEN
                        signal sqlstate '45000' set message_text = 'Turno errato';
					end if;
				WHEN 'FASE A GIRONI' THEN 
					IF (@lastPhase ='SEMIFINALE' OR @lastPhase = 'QUARTI' OR @lastPhase = 'FINALE' or @lastPhase = 'OTTAVI') THEN 
						signal sqlstate '45000' set message_text = 'Una partita giocata durante la fase a gironi non può avere data successiva rispetto alle partite nelle fasi seguenti';
					END IF;
				WHEN 'OTTAVI' THEN 
					IF (@lastPhase ='SEMIFINALE' OR @lastPhase = 'QUARTI' OR @lastPhase = 'FINALE') THEN 
						signal sqlstate '45000' set message_text = 'Una partita giocata agli ottavi non può avere data successiva alle partite delle fasi seguenti';
					END IF;
				WHEN 'QUARTI' THEN
					IF(@lastPhase ='SEMIFINALE' OR @lastPhase = 'FINALE') THEN
						signal sqlstate '45000' set message_text = 'Una partita giocata ai quarti non può avere data successiva alle partite giocate in semifinale o in finale';
					END IF;
				WHEN 'SEMIFINALE' THEN
					IF(@lastPhase = 'FINALE') THEN
						signal sqlstate '45000' set message_text = 'Una semifinale non può avere data successiva rispetto alla finale';
					END IF;
				END CASE;
		END IF;
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
